name: Android CI

on:
  push:
    branches: [ "f-droid-test-25000" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x lint 
      # run: ./gradlew build --debug
      
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: '**/*.apk'
